{% set name = "pyqtconsole" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyqtconsole-{{ version }}.tar.gz
  sha256: cdd2dfce0ddb69a9075debd4aada703fed39cf1ab0820ecd0ad69521826448c1

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - jedi
    - python >={{ python_min }}
    - qtpy

test:
  imports:
    - pyqtconsole
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/marcus-oscarsson/pyqtconsole
  summary: Light weight python interpreter, easy to embed into Qt applications
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
